apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
  labels:
    kubernetes.io/metadata.name: my-demo-app
  name: my-demo-app
spec:
  finalizers:
  - kubernetes

